# Generated by Django 4.1.3 on 2023-02-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clg_data',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
