# Generated by Django 4.1.3 on 2023-02-20 18:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_clg_data_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('subtitle', models.CharField(max_length=220)),
                ('blog_image', models.ImageField(upload_to='media')),
                ('content', tinymce.models.HTMLField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
