# Generated by Django 4.1.3 on 2023-02-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(upload_to='post_image'),
        ),
    ]
